#!/bin/bash

install_i3(){
  pacman -Q manjaro-i3-settings &> /dev/null
  local installed=$?
  if [ $installed == 0 ]
  then
    echo 'i3 is already installed.'
  else
    sudo pacman -S manjaro-i3-settings
    echo 'Successfully installed i3!'
  fi
}

install_dunst(){
  pacman -Q dunst &> /dev/null
  local installed=$?
  if [ $installed == 0 ]
  then
    echo 'dunst is already installed.'
  else
    sudo pacman -S dunst
    echo 'Successfully installed dunst!'
  fi
}

install_i3
install_dunst
